"""
Logic2Test - Generate tests from Code2Logic output files.

This package reads YAML, Hybrid YAML, or TOON format files generated by code2logic
and produces various types of tests (unit tests, integration tests, property tests).

Usage:
    from logic2test import TestGenerator
    
    generator = TestGenerator('project.c2l.yaml')
    generator.generate_unit_tests('tests/')
"""

from .generator import TestGenerator, GeneratorConfig, GenerationResult
from .parsers import LogicParser
from .templates import TestTemplate

__version__ = '1.0.40'
__all__ = ['TestGenerator', 'GeneratorConfig', 'GenerationResult', 'LogicParser', 'TestTemplate']
