"""
Logic2Code - Generate source code from Code2Logic output files.

This package reads YAML, Hybrid YAML, or TOON format files generated by code2logic
and produces source code scaffolds with proper structure, type hints, and docstrings.

Usage:
    from logic2code import CodeGenerator
    
    generator = CodeGenerator('project.c2l.yaml')
    generator.generate('output/')
"""

from .generator import CodeGenerator, GeneratorConfig, GenerationResult
from .renderers import PythonRenderer

__version__ = '1.0.34'
__all__ = ['CodeGenerator', 'GeneratorConfig', 'GenerationResult', 'PythonRenderer']
